# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('country_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fea_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30)),
                ('typeInShort', models.CharField(default='Regulator', max_length=30)),
                ('country_no', models.CharField(default='00', max_length=5)),
                ('features', models.ManyToManyField(to='myweb.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodId', models.IntegerField(default=0)),
                ('specification_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationGroupValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodId', models.IntegerField(default=0)),
                ('specificationId', models.IntegerField(default=0)),
                ('vlaueIndex', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='type_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.GoodType'),
        ),
    ]
