# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fea_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30)),
                ('gas', models.CharField(max_length=20)),
                ('max_inlet_pressure', models.FloatField(default=0)),
                ('max_outlet_pressure', models.FloatField(default=0)),
                ('inlet_connection', models.CharField(max_length=10)),
                ('outlet_connection', models.CharField(max_length=20)),
                ('features', models.ManyToManyField(to='myweb.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='type_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.GoodType'),
        ),
    ]
