# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='typeInShort',
            field=models.CharField(default='Regulator', max_length=30),
        ),
    ]
