# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-06 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='goodId',
        ),
    ]
