# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-03 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_goods_typeinshort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_no', models.IntegerField(primary_key=True, serialize=False)),
                ('countrt_text', models.CharField(max_length=50)),
            ],
        ),
    ]
