# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-03 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_no',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
