# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-06 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20190406_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationgroupvalue',
            old_name='vlaueIndex',
            new_name='valueIndex',
        ),
    ]
