# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-03 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_auto_20190303_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='country_no',
            field=models.CharField(default='00', max_length=5),
        ),
    ]
